# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job2
metadata:
  namespace: test
  name: test
spec:
  backoffLimit: 25
  template:
    metadata:
      annotations:
    spec:
      restartPolicy: Never
      - name: cosign
        image: cgr.dev/chainguard/cosign:latest@sha256:a8aeacbaf0a1176ab5dbcf9b73a517665d8db5e1495ba97d64c73b3821deb0d8
